-- ⛔ REVERTIDA. NO VOLVER A APLICAR. Ver migration_046.
--
-- Esta política abría la lectura de `classes` a todo el mundo, para que la
-- grilla se viera en la web pública. El problema: el PORTAL DEL SOCIO no
-- filtraba por gym_id — confiaba en RLS para aislarse. Al abrir la tabla, a los
-- socios de un estudio les aparecieron las clases de TODOS los gimnasios y
-- demos ("Pilates Reformer", "Danza Contemporánea", decenas de "Funcional").
--
-- Lección: el aislamiento entre clientes no puede depender de una sola capa.
-- Ahora las consultas filtran por gym_id A MANO, y la web pública lee las
-- clases desde el servidor con el service role, sin tocar RLS.
--
-- Se deja el archivo como registro de lo que se hizo y por qué se deshizo.

-- drop policy if exists "clases lectura pública" on public.classes;
-- create policy "clases lectura pública" on public.classes
--   for select using (true);
